services:
    splunk:
      image: splunk/splunk:latest
      container_name: so1
      hostname: so1
      ports:
        - "8000:8000"  # Web UI
        - "8088:8088"  # HTTP Event Collector

      environment:
        - SPLUNK_PASSWORD=my_passsword
        - SPLUNK_START_ARGS=--accept-license
        - SPLUNK_LICENSE_URI=Free
        - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
        - SPLUNK_HEC_TOKEN=12345678-1234-1234-1234-123456789012
      stdin_open: true
      tty: true 
      volumes:
        - ./logs:/opt/splunk/var/log/skip
        - splunk_data:/opt/splunk/var
        - ./splunk_config:/opt/splunk/etc/system/local

volumes:
  splunk_data: