version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: my_mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password_here
      MYSQL_DATABASE: my_database_name
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_user_password_here
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf # Adicione esta linha para montar o arquivo de configuração
      # Opcional: Se você tiver arquivos .sql para inicializar o banco de dados, pode adicioná-los aqui:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge